import { RecipeResponse } from './types';

export const data: RecipeResponse = {
  q: 'chicken, banana, onion',
  from: 0,
  to: 10,
  more: true,
  count: 159,
  hits: [
    {
      recipe: {
        uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_ad981673c2e76c13f2f52790aac9ce2e',
        label: 'Lentil Curry Stew',
        image: 'https://source.unsplash.com/random/',
        source: 'Food52',
        url: 'https://food52.com/recipes/8458-lentil-curry-stew',
        shareAs:
          'http://www.edamam.com/recipe/lentil-curry-stew-ad981673c2e76c13f2f52790aac9ce2e/chicken%2C+banana%2C+onion',
        yield: 2,
        dietLabels: [],
        healthLabels: [
          'Peanut-Free',
          'Tree-Nut-Free',
          'Alcohol-Free',
          'Sulfite-Free',
        ],
        cautions: ['Tree-Nuts', 'Sulfites'],
        ingredientLines: [
          '1 garlic clove',
          '1/2 onion',
          '1/2 cup ground beef (or quorn mince)',
          '1 carrot, minced',
          '1 cup red lentil',
          '1/2 cup edamame',
          'Chicken broth (or vegetable broth)',
          '1 tablespoon apple cider vinegar',
          '1 pinch curry powder',
          'Dashes salt and pepper to taste',
          'Splashes coconut milk',
          '1 handful small banana',
          'Handfuls dried coconut (unsweetened)',
        ],
        ingredients: [
          {
            text: '1 garlic clove',
            weight: 3,
            foodCategory: 'vegetables',
            foodId: 'food_avtcmx6bgjv1jvay6s6stan8dnyp',
            image:
              'https://www.edamam.com/food-img/6ee/6ee142951f48aaf94f4312409f8d133d.jpg',
          },
        ],
        calories: 1211.0510000005602,
        totalWeight: 644.1000000002024,
        totalTime: 116,
        cuisineType: ['indian'],
        mealType: ['lunch/dinner'],
        dishType: ['main course'],
        totalNutrients: {
          ENERC_KCAL: {
            label: 'Energy',
            quantity: 1211.0510000005602,
            unit: 'kcal',
          },
        },
        totalDaily: {
          ENERC_KCAL: {
            label: 'Energy',
            quantity: 60.552550000028006,
            unit: '%',
          },
        },
        digest: [
          {
            label: 'Protein',
            tag: 'PROCNT',
            schemaOrgTag: 'proteinContent',
            total: 77.70838750002494,
            hasRDI: true,
            daily: 155.41677500004988,
            unit: 'g',
          },
        ],
      },
    },
    {
      recipe: {
        uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_5cb28f4bea3d415932a69057d94d2bfc',
        label: 'Lamb Banana Curry',
        image: 'https://source.unsplash.com/random/',
        source: 'Tasting Table',
        url: 'https://www.tastingtable.com/entry_detail/chefs_recipes/6416/A_sweet_savory_twist_on_Southwestern_game.htm',
        shareAs:
          'http://www.edamam.com/recipe/lamb-banana-curry-5cb28f4bea3d415932a69057d94d2bfc/chicken%2C+banana%2C+onion',
        yield: 4,
        dietLabels: [],
        healthLabels: ['Mediterranean', 'Peanut-Free', 'Tree-Nut-Free'],
        cautions: ['Sulfites'],
        ingredientLines: [
          '¼ cup sweet yellow curry powder',
          '2 tablespoons extra-virgin olive oil',
          '1 cup finely chopped yellow onion (about 1 medium onion)',
          '2 tablespoons finely chopped fresh ginger (about 1½-inch piece of ginger)',
          '4 cloves finely chopped garlic',
          '2½ pounds lamb shoulder, cut into 1-inch cubes',
          '2 bananas, peeled and cut into ½-inch slices',
          '1 tablespoon ground cumin',
          '1 tablespoon ground coriander',
          '1 cup dry red wine',
          '6 cups chicken stock',
          'Kosher salt and freshly ground black pepper',
          '2 cups cooked jasmine rice, for serving',
        ],
        ingredients: [
          {
            text: '¼ cup sweet yellow curry powder',
            weight: 25.200000000426055,
            foodCategory: 'Condiments and sauces',
            foodId: 'food_ao4koeoajh7yjxaq2knzrbv55y8o',
            image:
              'https://www.edamam.com/food-img/9ce/9ce02a2887385fd2adaec8dd8adcf9c5.jpg',
          },
        ],
        calories: 4813.765782366473,
        totalWeight: 3668.3597084461067,
        totalTime: 150,
        cuisineType: ['indian'],
        mealType: ['lunch/dinner'],
        dishType: ['main course'],
        totalNutrients: {
          ENERC_KCAL: {
            label: 'Energy',
            quantity: 4813.765782366473,
            unit: 'kcal',
          },
        },
        totalDaily: {
          ENERC_KCAL: {
            label: 'Energy',
            quantity: 240.68828911832364,
            unit: '%',
          },
        },
        digest: [
          {
            label: 'Fat',
            tag: 'FAT',
            schemaOrgTag: 'fatContent',
            total: 298.17901238702325,
            hasRDI: true,
            daily: 458.73694213388194,
            unit: 'g',
          },
        ],
      },
    },
    {
      recipe: {
        uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_a1404e1f0b1cf669727dea4538130860',
        label: 'Yucatán Lime And Chicken Soup',
        image: 'https://source.unsplash.com/random/',
        source: 'Food & Wine',
        url: 'http://www.foodandwine.com/recipes/yucatan-lime-and-chicken-soup',
        shareAs:
          'http://www.edamam.com/recipe/yucat%C3%A1n-lime-and-chicken-soup-a1404e1f0b1cf669727dea4538130860/chicken%2C+banana%2C+onion',
        yield: 18,
        dietLabels: ['Low-Carb'],
        healthLabels: [
          'Sugar-Conscious',
          'Mediterranean',
          'Peanut-Free',
          'Tree-Nut-Free',
          'Alcohol-Free',
          'Sulfite-Free',
        ],
        cautions: ['Eggs', 'Milk', 'Sulfites'],
        ingredientLines: [
          '4 medium tomatoes',
          '1 large white onion, unpeeled, plus 1/2 cup minced onion, for garnish',
          '21 garlic cloves, peeled (2 heads)',
          '3 whole chicken breasts on the bone (about 1 1/4 pounds each)',
          '3 quarts chicken stock, low-sodium broth or water',
          '2 limes, zest finely grated and limes halved, plus wedges for serving',
          '20 allspice berries',
          '1 tablespoon dried oregano, preferably Mexican, plus more for sprinkling',
          'Salt and freshly ground pepper',
          '1 cup plus 2 tablespoons vegetable oil',
          '6 large scallions, minced',
          'Twelve 6-inch corn tortillas, cut into thin strips',
          '2 banana chiles or jalapeños, seeded and minced',
        ],
        ingredients: [
          {
            text: '4 medium tomatoes',
            weight: 492,
            foodCategory: 'vegetables',
            foodId: 'food_a6k79rrahp8fe2b26zussa3wtkqh',
            image:
              'https://www.edamam.com/food-img/23e/23e727a14f1035bdc2733bb0477efbd2.jpg',
          },
        ],
        calories: 5322.789500562203,
        totalWeight: 6046.004906458406,
        totalTime: 0,
        cuisineType: ['mexican'],
        mealType: ['lunch/dinner'],
        dishType: ['soup'],
        totalNutrients: {
          ENERC_KCAL: {
            label: 'Energy',
            quantity: 5322.789500562203,
            unit: 'kcal',
          },
          FAT: {
            label: 'Fat',
            quantity: 308.70141121901634,
            unit: 'g',
          },
        },
        totalDaily: {
          ENERC_KCAL: {
            label: 'Energy',
            quantity: 266.13947502811016,
            unit: '%',
          },
        },
        digest: [
          {
            label: 'Fat',
            tag: 'FAT',
            schemaOrgTag: 'fatContent',
            total: 308.70141121901634,
            hasRDI: true,
            daily: 474.9252480292559,
            unit: 'g',
          },
        ],
      },
    },
  ],
};
